# Importing libraries

In [2]:
%tensorflow_version 2.x

In [3]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [4]:
tf.__version__

'2.5.0'

# Data Preprocessing



## Importing Dataset


In [5]:
df = pd.read_csv('/content/drive/MyDrive/ML Tasks/Machine Learning A-Z (Codes and Datasets)/Part 8 - Deep Learning/Section 39 - Artificial Neural Networks (ANN)/Python/Churn_Modelling.csv')
x = df.iloc[: , 3:-1].values
y = df.iloc[:, -1].values

In [6]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [7]:
y

array([1, 0, 1, ..., 1, 1, 0])



## Encoding Categorical Data



In [8]:
# Encoding Gender Column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [9]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [10]:
#  one Hot Encoding Geography Column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers= [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [11]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]




## Splitting into Training set and test set




In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)



## Feature Scaling



In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [14]:
print(x_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


# Building the ANN



## Initialising the ANN 



In [15]:
ann = tf.keras.models.Sequential()



> Adding the input layer and the first hidden layer



In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))



## Adding the second hidden layer 



In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))



## Adding the Output Layer



In [18]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
# for non-binary Classification we use the activation = 'softmax'

# Training the ANN

## Compiling the ANN

In [19]:
ann.compile(optimizer='adam', loss='binary_crossentropy' ,metrics= ['accuracy'])
# for binary clasification the loss = 'binary_crossentropy' and for non- binary classifications we use loss = 'categorical_crossentropy'

## Training the ANN on the Training Set

In [20]:
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5527 - accuracy: 0.7484
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4668 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4497 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4412 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4350 - accuracy: 0.7961
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4302 - accuracy: 0.7974
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4263 - accuracy: 0.8002
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4224 - accuracy: 0.8046
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4180 - accuracy: 0.8154
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4129 - accura

# Making the predictions and evaluating the model

In [21]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


## Predicting the test set result

In [22]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Confusion Matrix

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1534   61]
 [ 256  149]]


0.8415